# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doi', models.CharField(max_length=100)),
                ('aerobic_status', models.CharField(choices=[('aerobe', 'aerobe'), ('facultative anaerobe', 'facultative anaerobe'), ('microaerobe', 'microaerobe'), ('obligate anaerobe', 'obligate anaerobe'), ('not indicated', 'not indicated')], max_length=100)),
                ('morphology', models.CharField(choices=[('rods', 'rods'), ('slightly curved rods', 'slightly curved rods'), ('cocci', 'cocci'), ('not indicated', 'not indicated')], max_length=100)),
                ('motility', models.CharField(choices=[('spore forming', 'spore forming'), ('non-spore forming', 'non-spore forming'), ('not indicated', 'not indicated')], max_length=100)),
                ('gram_stain', models.CharField(choices=[('Gram-positive', 'Gram-positive'), ('Gram-negative', 'Gram-negative'), ('Gram variable', 'Gram variable'), ('not indicated', 'not indicated')], max_length=100)),
                ('bile_sensitive', models.CharField(choices=[('growth in 20% bile', 'growth in 20% bile'), ('no growth in 20% bile', 'no growth in 20% bile'), ('not indicated', 'not indicated')], max_length=100)),
                ('saccharolytic', models.CharField(choices=[('saccharolytic', 'saccharolytic'), ('asaccharolytic', 'asaccharolytic'), ('not indicated', 'not indicated')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'genera',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doi', models.CharField(max_length=100)),
                ('aerobic_status', models.CharField(choices=[('aerobe', 'aerobe'), ('facultative anaerobe', 'facultative anaerobe'), ('microaerobe', 'microaerobe'), ('obligate anaerobe', 'obligate anaerobe'), ('not indicated', 'not indicated')], max_length=100)),
                ('morphology', models.CharField(choices=[('rods', 'rods'), ('slightly curved rods', 'slightly curved rods'), ('cocci', 'cocci'), ('not indicated', 'not indicated')], max_length=100)),
                ('motility', models.CharField(choices=[('spore forming', 'spore forming'), ('non-spore forming', 'non-spore forming'), ('not indicated', 'not indicated')], max_length=100)),
                ('gram_stain', models.CharField(choices=[('Gram-positive', 'Gram-positive'), ('Gram-negative', 'Gram-negative'), ('Gram variable', 'Gram variable'), ('not indicated', 'not indicated')], max_length=100)),
                ('bile_sensitive', models.CharField(choices=[('growth in 20% bile', 'growth in 20% bile'), ('no growth in 20% bile', 'no growth in 20% bile'), ('not indicated', 'not indicated')], max_length=100)),
                ('saccharolytic', models.CharField(choices=[('saccharolytic', 'saccharolytic'), ('asaccharolytic', 'asaccharolytic'), ('not indicated', 'not indicated')], max_length=100)),
                ('urease', models.CharField(choices=[('urease positive', 'urease positive'), ('urease negative', 'urease negative'), ('not indicated', 'not indicated')], max_length=20)),
                ('catalase', models.CharField(choices=[('catalase positive', 'catalase positive'), ('catalase negative', 'catalase negative'), ('not indicated', 'not indicated')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'species',
            },
        ),
    ]
