# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genus',
            name='comments',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='species',
            name='comments',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
