# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb0', '0002_auto_20170711_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='genus',
            name='spore_formation',
            field=models.CharField(choices=[('spore forming', 'spore forming'), ('non-spore forming', 'non-spore forming'), ('not indicated', 'not indicated')], default='non-spore forming', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='spore_formation',
            field=models.CharField(choices=[('spore forming', 'spore forming'), ('non-spore forming', 'non-spore forming'), ('not indicated', 'not indicated')], default='non-spore forming', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genus',
            name='morphology',
            field=models.CharField(choices=[('rods', 'rods'), ('slightly curved rods', 'slightly curved rods'), ('cocci', 'cocci'), ('oval-shaped', 'oval-shaped'), ('fusiform', 'fusiform'), ('not indicated', 'not indicated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='genus',
            name='motility',
            field=models.CharField(choices=[('motile', 'motile'), ('non-motile', 'non-motile'), ('not indicated', 'not indicated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='morphology',
            field=models.CharField(choices=[('rods', 'rods'), ('slightly curved rods', 'slightly curved rods'), ('cocci', 'cocci'), ('oval-shaped', 'oval-shaped'), ('fusiform', 'fusiform'), ('not indicated', 'not indicated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='motility',
            field=models.CharField(choices=[('motile', 'motile'), ('non-motile', 'non-motile'), ('not indicated', 'not indicated')], max_length=100),
        ),
    ]
