# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb0', '0003_auto_20170712_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='acetate_production',
            field=models.CharField(choices=[('consumed', 'consumed'), ('major product', 'major product'), ('minor product', 'minor product'), ('not producted', 'not producted'), ('not indicated', 'not indicated')], default='---------', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='butyrate_production',
            field=models.CharField(choices=[('consumed', 'consumed'), ('major product', 'major product'), ('minor product', 'minor product'), ('not producted', 'not producted'), ('not indicated', 'not indicated')], default='---------', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='formate_production',
            field=models.CharField(choices=[('consumed', 'consumed'), ('major product', 'major product'), ('minor product', 'minor product'), ('not producted', 'not producted'), ('not indicated', 'not indicated')], default='---------', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='isobutyrate_production',
            field=models.CharField(choices=[('consumed', 'consumed'), ('major product', 'major product'), ('minor product', 'minor product'), ('not producted', 'not producted'), ('not indicated', 'not indicated')], default='---------', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='isovalerate_production',
            field=models.CharField(choices=[('consumed', 'consumed'), ('major product', 'major product'), ('minor product', 'minor product'), ('not producted', 'not producted'), ('not indicated', 'not indicated')], default='---------', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='propionate_production',
            field=models.CharField(choices=[('consumed', 'consumed'), ('major product', 'major product'), ('minor product', 'minor product'), ('not producted', 'not producted'), ('not indicated', 'not indicated')], default='---------', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='valerate_production',
            field=models.CharField(choices=[('consumed', 'consumed'), ('major product', 'major product'), ('minor product', 'minor product'), ('not producted', 'not producted'), ('not indicated', 'not indicated')], default='---------', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genus',
            name='gram_stain',
            field=models.CharField(choices=[('Gram-positive', 'Gram-positive'), ('Gram-negative', 'Gram-negative'), ('Gram-variable', 'Gram-variable'), ('not indicated', 'not indicated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='genus',
            name='morphology',
            field=models.CharField(choices=[('rod/ bacilli', 'rod/ bacilli'), ('slightly curved rods', 'slightly curved rods'), ('cocci', 'cocci'), ('oval-shaped/ coccobaccili', 'oval-shaped/ coccobaccili'), ('fusiform', 'fusiform'), ('rods or oval-shaped', 'rods or oval-shaped'), ('cocci or oval-shaped', 'cocci or oval-shaped'), ('rods or slightly curved rods', 'rods or slightly curved rods'), ('ovoid', 'ovoid'), ('not indicated', 'not indicated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='genus',
            name='motility',
            field=models.CharField(choices=[('motile', 'motile'), ('non-motile', 'non-motile'), ('variable', 'variable'), ('not indicated', 'not indicated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='genus',
            name='spore_formation',
            field=models.CharField(choices=[('spore forming', 'spore forming'), ('non-spore forming', 'non-spore forming'), ('mixed', 'mixed'), ('not indicated', 'not indicated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='gram_stain',
            field=models.CharField(choices=[('Gram-positive', 'Gram-positive'), ('Gram-negative', 'Gram-negative'), ('Gram-variable', 'Gram-variable'), ('not indicated', 'not indicated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='morphology',
            field=models.CharField(choices=[('rod/ bacilli', 'rod/ bacilli'), ('slightly curved rods', 'slightly curved rods'), ('cocci', 'cocci'), ('oval-shaped/ coccobaccili', 'oval-shaped/ coccobaccili'), ('fusiform', 'fusiform'), ('rods or oval-shaped', 'rods or oval-shaped'), ('cocci or oval-shaped', 'cocci or oval-shaped'), ('rods or slightly curved rods', 'rods or slightly curved rods'), ('ovoid', 'ovoid'), ('not indicated', 'not indicated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='motility',
            field=models.CharField(choices=[('motile', 'motile'), ('non-motile', 'non-motile'), ('variable', 'variable'), ('not indicated', 'not indicated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='spore_formation',
            field=models.CharField(choices=[('spore forming', 'spore forming'), ('non-spore forming', 'non-spore forming'), ('mixed', 'mixed'), ('not indicated', 'not indicated')], max_length=100),
        ),
    ]
